[book]
authors = ["panpilkarz"]
language = "en"
multilingual = false
src = "src"
title = "Rust vs Python"

[output.html]
git-repository-url = "https://github.com/panpilkarz/rust-vs-python"

[output.html.search]
enable = true
